# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Evaluateteam.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import mysql.connector as c
con=c.connect(host="localhost",user="root",passwd="16239",database="project_fantasy")
cursor=con.cursor()


class Ui_EvaluateTeam(object):
    
    def setupUi(self, EvaluateTeam):
        EvaluateTeam.setObjectName("EvaluateTeam")
        EvaluateTeam.resize(509, 542)
        self.verticalLayout = QtWidgets.QVBoxLayout(EvaluateTeam)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(EvaluateTeam)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_4 = QtWidgets.QLabel(EvaluateTeam)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.Box1 = QtWidgets.QComboBox(EvaluateTeam)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        self.Box1.setFont(font)
        self.Box1.setObjectName("Box1")
        self.horizontalLayout.addWidget(self.Box1)
        spacerItem = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label_5 = QtWidgets.QLabel(EvaluateTeam)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.Box2 = QtWidgets.QComboBox(EvaluateTeam)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        self.Box2.setFont(font)
        self.Box2.setObjectName("Box2")
        self.Box2.addItem("")
        self.horizontalLayout.addWidget(self.Box2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.line = QtWidgets.QFrame(EvaluateTeam)
        self.line.setMinimumSize(QtCore.QSize(491, 0))
        self.line.setMaximumSize(QtCore.QSize(491, 31))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.label_2 = QtWidgets.QLabel(EvaluateTeam)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem6)
        self.label_3 = QtWidgets.QLabel(EvaluateTeam)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem7)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem8)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem9)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem10)
        self.list1 = QtWidgets.QListWidget(EvaluateTeam)
        self.list1.setObjectName("list1")
        self.horizontalLayout_3.addWidget(self.list1)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem11)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem12)
        self.list2 = QtWidgets.QListWidget(EvaluateTeam)
        self.list2.setObjectName("list2")
        self.horizontalLayout_3.addWidget(self.list2)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem13)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.label_6 = QtWidgets.QLabel(EvaluateTeam)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(9)
        self.label_6.setFont(font)
        self.label_6.setText("")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.btn1 = QtWidgets.QPushButton(EvaluateTeam)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(9)
        self.btn1.setFont(font)
        self.btn1.setObjectName("btn1")
        self.verticalLayout.addWidget(self.btn1)
        self.evaluate()##
        self.btn1.clicked.connect(self.cal)##

        self.retranslateUi(EvaluateTeam)
        QtCore.QMetaObject.connectSlotsByName(EvaluateTeam)

    def retranslateUi(self, EvaluateTeam):
        _translate = QtCore.QCoreApplication.translate
        EvaluateTeam.setWindowTitle(_translate("EvaluateTeam", "Form"))
        self.label.setText(_translate("EvaluateTeam", "Evalute performance of  your fantay team"))
        self.label_4.setText(_translate("EvaluateTeam", "Select Team"))
        self.label_5.setText(_translate("EvaluateTeam", "Select Match"))
        self.Box2.setItemText(0, _translate("EvaluateTeam", "match1"))
        self.label_2.setText(_translate("EvaluateTeam", "Players"))
        self.label_3.setText(_translate("EvaluateTeam", "Points"))
        self.btn1.setText(_translate("EvaluateTeam", "CALCULATE SCORE"))

    def evaluate(self):
        self.list1.clear()
        cursor=con.cursor()
        query="select name from team;"
        cursor.execute(query)
        row=cursor.fetchall()
        team=[]
        a=0
        for x in row:
            txt=str(row[a]).replace("(","").replace("'","").replace("'","").replace(",","").replace(")","")
            team.append(txt)
            self.Box1.addItem(txt)
            a=a+1

    def cal(self):
        text=self.Box1.currentText()
        query2="select players,value from team where name='"+text+"';"
        cursor.execute(query2)
        row=cursor.fetchone()
        rec=row[0].split(',')
        self.list1.addItems(rec)
        self.list2.clear()
        teamttl=0
        for i in range(self.list1.count()):
            ttl, batscore, bowlscore, fieldscore=0,0,0,0
            name=self.list1.item(i).text()
            cursor.execute("select * from match1 where player='"+name+"'")
            row=cursor.fetchone()
            batscore=int(row[1]/2)
            if batscore>=50: batscore+=5
            if batscore>=100: batscore+=10
            if row[1]>0:
                sr=row[1]/row[2]
                if sr>=80 and sr<100: batscore+=2
                if sr>=100:batscore+=4
            batscore=batscore+row[3]
            batscore=batscore+2*row[4]
            bowlscore=row[8]*10
            if row[8]>=3: bowlscore=bowlscore+5
            if row[8]>=5: bowlscore=bowlscore=bowlscore+10
            if row[7]>0:
                er=6*row[7]/row[5]
                if er<=2: bowlscore=bowlscore+10
                if er>2 and er<=3.5: bowlscore=bowlscore+7
                if er>3.5 and er<=4.5: bowlscore=bowlscore+4
            fieldscore=(row[9]+row[10]+row[11])*10
            ttl=batscore+bowlscore+fieldscore
            self.list2.addItem(str(ttl))
            teamttl=teamttl+ttl
            text="Total score = "+str(teamttl)
        self.label_6.setText(str(text))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    EvaluateTeam = QtWidgets.QWidget()
    ui = Ui_EvaluateTeam()
    ui.setupUi(EvaluateTeam)
    EvaluateTeam.show()
    sys.exit(app.exec_())










