# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Openteam.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from Evaluateteam import Ui_EvaluateTeam
import mysql.connector as c
con=c.connect(host="localhost",user="root",passwd="16239",database="project_fantasy")
cursor=con.cursor()


class Ui_Openteam1(object):
    def openwindow(self):
        self.window = QtWidgets.QWidget()
        self.ui = Ui_EvaluateTeam()
        self.ui.setupUi(self.window)
        self.window.show()
        
    def setupUi(self, Openteam1):
        Openteam1.setObjectName("Openteam1")
        Openteam1.resize(529, 505)
        self.verticalLayout = QtWidgets.QVBoxLayout(Openteam1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtWidgets.QLabel(Openteam1)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.Box1 = QtWidgets.QComboBox(Openteam1)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(9)
        self.Box1.setFont(font)
        self.Box1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Box1.setObjectName("Box1")
        self.horizontalLayout_2.addWidget(self.Box1)
        self.btn2 = QtWidgets.QPushButton(Openteam1)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        self.btn2.setFont(font)
        self.btn2.setObjectName("btn2")
        self.horizontalLayout_2.addWidget(self.btn2)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.label_2 = QtWidgets.QLabel(Openteam1)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(8)
        font.setUnderline(True)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.list1 = QtWidgets.QListWidget(Openteam1)
        self.list1.setObjectName("list1")
        self.horizontalLayout.addWidget(self.list1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.btn1 = QtWidgets.QPushButton(Openteam1)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.btn1.setFont(font)
        self.btn1.setObjectName("btn1")
        self.verticalLayout.addWidget(self.btn1)
        self.open()##
        self.btn1.clicked.connect(self.evaluate_team)####evaluate window opening
        self.btn2.clicked.connect(self.Enter)##

        self.retranslateUi(Openteam1)
        QtCore.QMetaObject.connectSlotsByName(Openteam1)

    def retranslateUi(self, Openteam1):
        _translate = QtCore.QCoreApplication.translate
        Openteam1.setWindowTitle(_translate("Openteam1", "Form"))
        self.label_3.setText(_translate("Openteam1", "YOUR FANTASY TEAM"))
        self.btn2.setText(_translate("Openteam1", "ENTER"))
        self.label_2.setText(_translate("Openteam1", "PLAYERS"))
        self.btn1.setText(_translate("Openteam1", "Evaluate Team"))

    def open(self):
        cursor=con.cursor()
        query="select name from team;"
        cursor.execute(query)
        row=cursor.fetchall()
        teams=[]
        a=0
        for x in row:
            txt=str(row[a]).replace(",","").replace("'","").replace("(","").replace(")","")
            teams.append(txt)
            self.Box1.addItem(txt)
            a=a+1
            
    def Enter(self):
        self.list1.clear()
        team=self.Box1.currentText()
        cursor=con.cursor()
        query2="select players,value from team where name='"+team+"';"
        cursor.execute(query2)
        row=cursor.fetchone()
        team=[]
        rec=row[0].split(',')
        self.list1.addItems(rec)
        self.used=row[1]
        self.avl=1000-row[1]

    def evaluate_team(self):
        self.openwindow()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Openteam1 = QtWidgets.QWidget()
    ui = Ui_Openteam1()
    ui.setupUi(Openteam1)
    Openteam1.show()
    sys.exit(app.exec_())
